apiVersion: v1
kind: Service
metadata:
  labels:
    app: vscode
    release: vscode
  name: code-server-nodeport
  namespace: {{ .Values.namespace }} 
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: vscode
    port: 8080
    protocol: TCP
    targetPort: code-server
  selector:
    app: code-server-{{ .Values.user }}
  sessionAffinity: None
  type: NodePort
