apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-server-job-executor
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: code-server-basic-job-executor
subjects:
- kind: ServiceAccount
  name: code-server-{{ .Values.user }}
  namespace: {{ .Values.namespace }} 
