apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ssh
    release: ssh
  name: ssh-saarc
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - command:
    - /bin/bash
    - /etc/config/shell/v3io-shell.sh
    env:
    - name: IGZ_NAMESPACE_DOMAIN
      value: {{ .Values.igzDomain }}
    - name: IGZ_VERSION
      value: {{ .Values.igzVersion }}
    - name: IGZ_DATA_CONFIG_FILE
      value: /igz/java/conf/v3io.conf
    - name: CURRENT_NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: V3IO_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: shell-v3io-auth
    - name: V3IO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: accessKey
          name: shell-v3io-auth
#    - name: HOME
#      value: /User
    - name: V3IO_HOME
      value: users/admin
    - name: V3IO_HOME_URL
      value: v3io://users/admin
    - name: V3IO_API
      value: v3io-webapi.{{ .Values.namespace }}.svc:8081
    image: ssh_server:latest
    imagePullPolicy: IfNotPresent
    name: ssh
    ports:
    - containerPort: 7681
      name: ttyd
      protocol: TCP
    - containerPort: 22
      name: sshd
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/config/shell
      name: config-volume
    - mountPath: /var/run/iguazio/daemon_health
      name: daemon-health
    - mountPath: /var/run/iguazio/secrets
      name: java-cert
    - mountPath: /dev/shm
      name: shm
    - mountPath: /var/run/iguazio/dayman
      name: v3iod-comm
    - mountPath: /etc/config/v3io
      name: v3io-config
    - mountPath: /igz/java/auth
      name: v3io-auth
    - mountPath: /v3io
      name: v3io-fuse
    - mountPath: /User
      name: v3io-fuse
      subPath: users//admin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: shell-service-admin-token-js84w
      readOnly: true
    - mountPath: /var/run/iguazio/secrets/ssh
      readOnly: true
      name: ssh-pub-key
#    workingDir: /User
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: iguazio-ssh
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: shell-service-admin
  serviceAccountName: shell-service-admin
  volumes:
  - configMap:
      defaultMode: 420
      name: ssh
    name: config-volume
  - emptyDir: {}
    name: daemon-health
  - emptyDir: {}
    name: java-cert
  - hostPath:
      path: /dev/shm/{{ .Values.namespace }}
      type: ""
    name: shm
  - hostPath:
      path: /var/run/iguazio/dayman/{{ .Values.namespace }}
      type: ""
    name: v3iod-comm
  - configMap:
      defaultMode: 420
      name: shell-v3io-config
    name: v3io-config
  - name: v3io-auth
    secret:
      defaultMode: 420
      secretName: shell-v3io-auth
  - flexVolume:
      driver: v3io/fuse
      options:
        dirsToCreate: '[{"name": "users//admin", "permissions": 488}]'
      secretRef:
        name: shell-v3io-fuse
    name: v3io-fuse
  - name: shell-service-admin-token-js84w
    secret:
      defaultMode: 420
      secretName: shell-service-admin-token-mrqjc 
  - name: ssh-pub-key
    secret:
      defaultMode: 420
      secretName: ssh-{{ .Values.user }}
