apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssh
    release: ssh
  name: ssh-nodeport
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: sshd
  selector:
    app: ssh
    release: ssh
  sessionAffinity: None
