apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: {{ .Values.namespace }} 
spec:
  ports:
  - name: ttyd
    port: 8080
    protocol: TCP
    targetPort: ttyd
  selector:
    app: ssh
    release: ssh
  sessionAffinity: None
  type: ClusterIP
